packages:
  - 'apps/*'
  - 'workers/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  es5-ext: false
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude: []

patchedDependencies:
  google-play-scraper: patches/google-play-scraper.patch
